"""Material léxico del generador sintético. Todo es inventado: no hay personas ni cuentas reales."""

from __future__ import annotations

ES_TEMPLATES = [
    "{OP} {S} está {INT} {GOOD}",
    "no puedo creer lo de {S}",
    "alguien más vio {O}? {OP} estuvo {INT} {BAD}",
    "{T} me puse a ver {O} y me quedé pensando en {S}",
    "{V:tener} que ver {O}, es {INT} {GOOD}",
    "qué {BAD} lo de {S}, {CONN} ya lo veía venir",
    "si {V:querer} entender {S} {V:mirar} {O}",
    "{V:saber} que {S} siempre fue así",
    "me encanta {O} {CONN} {S} me tiene cansado",
    "hace mucho que no veía algo tan {GOOD} como {O}",
    "{VOC} alguien sabe qué pasó con {S}?",
    "a ver si {T} hay novedades de {S}",
    "otra vez con {S}, en serio no aprenden más",
    "a veces pienso que {S} es {INT} {BAD} y después veo {O} y se me pasa",
    "tal vez {S} no sea para tanto, {CONN} {O} sí",
    "hoy no tengo ganas de hacer nada, {CONN} hay que {WORKV}",
    "estoy {INT} cansado, después veo qué hago con {O}",
    "gracias a todos por los mensajes, {OP} son {INT} {GOOD}",
    "bueno me voy a dormir que mañana hay que {WORKV}",
    "iba a hablar de {S} {CONN} mejor no digo nada",
    "hola {VOC}, alguien para hablar de {O}?",
    "quiero que vuelva {O}, era lo más {GOOD} que había",
    "no sé qué pensar de {S}, {V:pensar} que es para tanto?",
    "estaba mirando {O} y había un {KID} que decía que {S} es {GOOD}",
    "ahora resulta que {S} es {GOOD}, {V:mirar} {V:pron}",
    "también me pasa con {O}, no es solo {S}",
    "todo esto es porque nadie quiere hablar de {S}",
    "para mí {O} es lo mejor que le pasó a {S}",
    "estoy bien, solo un poco quemado con {S}",
    "tampoco es que {O} sea {INT} {GOOD}, {V:entender}?",
    "igual {S} me sigue pareciendo {GOOD}",
    "el fin de semana voy a ver {O}, alguien se suma?",
    "por favor que alguien me explique {S}",
    "me gasté toda la {MONEY} en {O} y no me arrepiento de nada",
    "qué {MESS} se armó con {S}",
    "el {KID} del {BUS} estaba hablando de {O}, {INT} {GOOD}",
    "hoy toca {BEER} y {O}",
    "{V:pron} {V:ser} de los que piensan que {S} es {BAD}?",
    "{V:decir} qué {V:pensar} de {O}",
    "cada vez que veo {S} me acuerdo de {O}",
    "desde que empezó {S} no paro de pensar en {O}",
    "lo de {S} es {INT} {BAD}, hasta mi vieja se dio cuenta",
    "no entiendo a la gente que defiende {S}",
    "mucho ruido con {S} y al final nada",
    "{T} vi {O} por primera vez y {OP} es {INT} {GOOD}",
    "es un hecho: {S} ya no es lo que era",
    "tuvo que pasar lo de {O} para que hablen de {S}",
    "{V:venir} a ver {O} conmigo y {V:contar} qué te parece",
    "{V:poder} creer que todavía discuten por {S}?",
    "{V:fijarse} en {O}, {OP} es {GOOD}",
]

EN_TEMPLATES = [
    "{OP} {S} is {INT} {GOOD}",
    "can't believe what happened with {S}",
    "did anyone else see {O}? {OP} it was {INT} {BAD}",
    "{T} i watched {O} and now i can't stop thinking about {S}",
    "you have to check out {O}, it's {INT} {GOOD}",
    "so {BAD} what's going on with {S}, {CONN} i saw it coming",
    "if you want to understand {S} just look at {O}",
    "you know {S} has always been like this",
    "i love {O} {CONN} {S} is wearing me out",
    "haven't seen anything as {GOOD} as {O} in a while",
    "{VOC} does anyone know what happened with {S}?",
    "people are sleeping on {O} because of {S}",
    "thanks everyone for the messages, you are {INT} {GOOD}",
    "i'm so tired, don't know what to do about {O}",
    "going to bed, got work tomorrow",
    "that's exactly why {S} is {BAD} though",
    "please someone explain {S} to me",
    "i don't get people who defend {S}",
    "a lot of noise about {S} and then nothing",
    "definitely watching {O} this weekend, who's in?",
    "which one is better, {O} or {S}? your call",
    "their take on {S} is {INT} {BAD}",
    "can't wait until {O} is back",
    "spent all my money on {O}, no regrets",
    "every time i see {S} i think of {O}",
    "are you one of those people who think {S} is {BAD}?",
    "{T} i saw {O} for the first time and {OP} it's {INT} {GOOD}",
    "not gonna lie {S} is kinda {GOOD}",
]

ES_SLOTS = {
    "OP": ["creo que", "me parece que", "para mí", "la verdad que", "siento que", "yo digo que",
           "posta que", "", "sinceramente", "ponele que", "onda"],
    "INT": ["muy", "re", "super", "bastante", "demasiado", "mega", "tan", "recontra"],
    "GOOD": ["bueno", "genial", "copado", "increíble", "zarpado", "lindo", "tremendo",
             "espectacular", "buenísimo", "una locura", "de diez", "joya"],
    "BAD": ["malo", "horrible", "pésimo", "un desastre", "flojo", "malísimo", "de terror",
            "una vergüenza", "cualquiera", "trucho"],
    "CONN": ["pero", "igual", "aunque", "y", "encima", "además", "o sea", "total"],
    "VOC": ["che", "", "gente", "amigos", "chicos", "bro", "loco", "boludo"],
    "T": ["hoy", "ayer", "anoche", "recién", "esta mañana", "el otro día", "hace un rato"],
    "WORKV": ["laburar", "trabajar", "currar"],
    "MONEY": ["plata", "guita", "dinero", "mangos"],
    "BUS": ["bondi", "colectivo", "bus"],
    "KID": ["pibe", "chico", "chabón", "tipo", "flaco", "tío"],
    "BEER": ["birra", "cerveza", "fernet"],
    "MESS": ["quilombo", "lío", "desastre", "bardo"],
}
RIO_ONLY = {"posta que", "ponele que", "onda", "re", "recontra", "copado", "zarpado", "joya",
            "trucho", "che", "boludo", "loco", "laburar", "guita", "mangos", "bondi", "pibe",
            "chabón", "flaco", "birra", "fernet", "quilombo", "bardo", "recién"}
NEUTRAL_ONLY = {"currar", "tío", "bus", "dinero"}

EN_SLOTS = {
    "OP": ["i think", "honestly", "tbh", "imo", "i feel like", "ngl", "", "personally", "lowkey"],
    "INT": ["very", "really", "so", "super", "pretty", "way too", "hella", "quite"],
    "GOOD": ["good", "great", "amazing", "awesome", "insane", "lovely", "solid", "fire",
             "brilliant", "neat"],
    "BAD": ["bad", "awful", "terrible", "a mess", "trash", "mid", "embarrassing", "a joke", "weak"],
    "CONN": ["but", "though", "and", "plus", "still", "i mean"],
    "VOC": ["", "guys", "folks", "yo", "hey", "bro", "y'all"],
    "T": ["today", "yesterday", "last night", "just now", "this morning", "the other day"],
}

V2 = {  # (voseo, tuteo)
    "tener": ("tenés", "tienes"), "querer": ("querés", "quieres"), "poder": ("podés", "puedes"),
    "saber": ("sabés", "sabes"), "mirar": ("mirá", "mira"), "fijarse": ("fijate", "fíjate"),
    "decir": ("decime", "dime"), "venir": ("vení", "ven"), "pensar": ("pensás", "piensas"),
    "ser": ("sos", "eres"), "pron": ("vos", "tú"), "contar": ("contame", "cuéntame"),
    "entender": ("entendés", "entiendes"),
}

FILLERS_ES = ["tipo", "o sea", "nada", "viste", "la verdad", "posta", "literal", "ponele",
              "igual", "bueno", "che", "en fin", "mal", "obvio", "ni idea", "qué sé yo"]
FILLERS_EN = ["like", "i mean", "literally", "honestly", "anyway", "well", "ok so", "idk"]

LAUGHS = ["jaja", "jajaja", "jajajaja", "jeje", "jsjs", "jajsjaj", "ajaja", "JAJAJA", "haha",
          "lol", "xd", "XD", "jajaj", "jjajaja", "kkk", "jiji", "hahaha", "lmao"]
EMOJIS = list("😂🤣❤😍🔥👏🙌😭😅🤔👍💪🎉😎🙏✨💙💛🥲😡🤡👀💀🤷🙄😴🍻⚽🎮🎶🚀📈🐶🐱🍕🧉🌎📚💻🎬🏆🤝😬🫠🥳😤💸🧠")
EMOTICONS = [":)", ":(", "xD", ":D", ";)", ":P", ":/", "<3", "^^", ":c", ":v", "-_-", ":3"]

# (patrón, reemplazo) — errores y grafías recurrentes que una persona repite
MISSPELL_RULES_ES = [
    (r"\ba ver\b", "haber"), (r"\bhay\b", "ay"), (r"\bvez\b", "ves"), (r"\bo sea\b", "osea"),
    (r"\ben serio\b", "enserio"), (r"\ba veces\b", "aveces"), (r"\btal vez\b", "talvez"),
    (r"\bhacer\b", "aser"), (r"\biba\b", "iva"), (r"\bhasta\b", "asta"), (r"\bhola\b", "ola"),
    (r"\bquiero\b", "kiero"), (r"\bfin de semana\b", "finde"), (r"\bpor favor\b", "porfa"),
    (r"\bpor favor\b", "xfa"), (r"\bhecho\b", "echo"), (r"\btuvo\b", "tubo"),
    (r"\bno sé\b", "nose"), (r"\bestaba\b", "estava"), (r"\bhabía\b", "havia"),
    (r"\bahora\b", "aora"), (r"\bhoy\b", "oy"), (r"\bempezó\b", "empesó"),
    (r"\bparece\b", "parese"), (r"\bllo", "yo"), (r"\bvuelva\b", "buelva"),
    (r"\bquizás\b", "quisas"), (r"\bsí\b", "sep"), (r"\bcreo\b", "kreo"),
]
MISSPELL_RULES_EN = [
    (r"\ba lot\b", "alot"), (r"\bdefinitely\b", "definately"), (r"\bwhich\b", "wich"),
    (r"\btheir\b", "thier"), (r"\bbecause\b", "becuase"), (r"\buntil\b", "untill"),
    (r"\bgoing to\b", "gonna"), (r"\bpeople\b", "ppl"), (r"\bthough\b", "tho"),
    (r"\bknow\b", "kno"), (r"\btomorrow\b", "tmrw"), (r"\bmessages\b", "msgs"),
]

TOPICS = {
    "futbol": {
        "S": ["el partido", "el técnico", "el arbitraje", "la selección", "el mercado de pases",
              "el VAR", "la defensa", "el clásico", "la dirigencia", "el nueve", "la tabla",
              "el descenso"],
        "O": ["el gol del domingo", "el resumen de la fecha", "la conferencia de prensa",
              "el compilado de atajadas", "la previa del clásico", "el penal de anoche",
              "la entrevista al capitán", "el debut del juvenil", "la final de la copa"],
        "S_en": ["the match", "the coach", "the referee", "the transfer window", "the defense",
                 "the derby"],
        "O_en": ["that goal on sunday", "the highlights", "the press conference",
                 "the penalty last night", "the cup final"],
        "tags": ["futbol", "fecha", "clasico", "seleccion", "gol", "var", "ligaprofesional",
                 "mercadodepases", "hinchada", "copa", "superclasico", "descenso"],
        "domains": ["canchallena.example", "pelotalibre.example", "tribuna.example",
                    "golazo.example", "estadisticasfc.example"],
    },
    "politica": {
        "S": ["el gobierno", "la oposición", "el congreso", "la inflación", "el presupuesto",
              "el debate", "la campaña", "el ministro", "la reforma", "el dólar", "la encuesta",
              "el decreto"],
        "O": ["el discurso de ayer", "la sesión del congreso", "la entrevista de anoche",
              "el informe de la consultora", "la conferencia del ministro", "el hilo sobre la reforma",
              "la nota sobre el presupuesto", "el debate presidencial"],
        "S_en": ["the government", "the opposition", "congress", "inflation", "the budget",
                 "the campaign"],
        "O_en": ["yesterday's speech", "the debate", "that interview last night",
                 "the poll numbers", "the thread about the reform"],
        "tags": ["politica", "elecciones", "congreso", "inflacion", "debate", "dolar", "reforma",
                 "presupuesto", "urgente", "ultimomomento", "encuestas", "decreto"],
        "domains": ["diariodelsur.example", "lapolitica.example", "chequeando.example",
                    "elcronista-demo.example", "radioabierta.example"],
    },
    "gaming": {
        "S": ["el parche nuevo", "el ranked", "el servidor", "la temporada", "el meta",
              "el lag", "la beta", "el matchmaking", "el pase de batalla", "el torneo",
              "la comunidad", "el nerf"],
        "O": ["el tráiler nuevo", "el stream de anoche", "la final del torneo", "el speedrun",
              "la partida de ayer", "el evento del finde", "la actualización", "el clip del clutch",
              "el modo cooperativo"],
        "S_en": ["the new patch", "ranked", "the servers", "the meta", "the battle pass",
                 "matchmaking"],
        "O_en": ["the new trailer", "last night's stream", "the tournament final",
                 "that clutch clip", "the update"],
        "tags": ["gaming", "esports", "ranked", "stream", "parche", "torneo", "clutch",
                 "indiegames", "speedrun", "lan", "gamer", "pcgaming"],
        "domains": ["clipsgg.example", "parchenotas.example", "torneosya.example",
                    "streamhub.example", "ranktracker.example"],
    },
    "musica": {
        "S": ["el disco nuevo", "el recital", "la banda", "el festival", "la gira", "el productor",
              "la escena", "el trap", "el rock nacional", "la lista de temas", "el sonido",
              "la entrada"],
        "O": ["el tema nuevo", "el show del sábado", "la sesión en vivo", "el videoclip",
              "la versión acústica", "el set del festival", "la colaboración", "el vinilo",
              "el cover"],
        "S_en": ["the new album", "the tour", "the band", "the festival", "the scene",
                 "ticket prices"],
        "O_en": ["the new single", "saturday's show", "the live session", "the music video",
                 "that cover"],
        "tags": ["musica", "recital", "disconuevo", "rock", "trap", "festival", "envivo", "gira",
                 "playlist", "vinilo", "indie", "nowplaying"],
        "domains": ["escuchalo.example", "rockdelsur.example", "entradasya.example",
                    "sesionesvivo.example", "discoteca-demo.example"],
    },
    "cripto": {
        "S": ["el mercado", "la suba", "la caída", "el halving", "la regulación", "el exchange",
              "la stablecoin", "el proyecto", "la comisión", "el airdrop", "la billetera",
              "el staking"],
        "O": ["el gráfico de hoy", "el hilo sobre el halving", "el informe semanal",
              "la charla del domingo", "el análisis técnico", "el anuncio del exchange",
              "la auditoría", "el whitepaper"],
        "S_en": ["the market", "the pump", "the dip", "regulation", "the exchange", "staking"],
        "O_en": ["today's chart", "the weekly report", "the audit", "the whitepaper",
                 "that thread about the halving"],
        "tags": ["cripto", "bitcoin", "btc", "eth", "hodl", "defi", "trading", "halving",
                 "altcoins", "blockchain", "airdrop", "staking"],
        "domains": ["graficos.example", "criptonoticias-demo.example", "exchangeya.example",
                    "onchain.example", "defipulse-demo.example"],
    },
    "cocina": {
        "S": ["el asado", "la receta", "la masa madre", "el horno", "la parrilla", "el chimichurri",
              "la milanesa", "el punto de la carne", "la pizza casera", "el mate", "la salsa",
              "el postre"],
        "O": ["la receta de mi abuela", "el pan de ayer", "el video de la parrilla",
              "el paso a paso", "la torta del domingo", "el locro", "las empanadas",
              "el guiso de lentejas"],
        "S_en": ["the recipe", "sourdough", "the grill", "the sauce", "homemade pizza",
                 "dessert"],
        "O_en": ["my grandma's recipe", "yesterday's bread", "the step by step",
                 "sunday's cake", "the stew"],
        "tags": ["cocina", "receta", "asado", "masamadre", "casero", "parrilla", "empanadas",
                 "pizza", "foodie", "postres", "mate", "locro"],
        "domains": ["recetario.example", "fuegos.example", "panycasa.example",
                    "cocinafacil-demo.example", "sabores.example"],
    },
    "tech": {
        "S": ["el deploy", "el framework", "la base de datos", "el bug", "la IA", "el código",
              "el sprint", "la documentación", "el servidor", "la migración", "el refactor",
              "la nube"],
        "O": ["el hilo sobre testing", "la charla de la conferencia", "el repo nuevo",
              "el tutorial", "el benchmark", "la release", "el postmortem", "el paper",
              "la demo"],
        "S_en": ["the deploy", "the framework", "the database", "the bug", "the codebase",
                 "the migration"],
        "O_en": ["the conference talk", "the new repo", "the tutorial", "the benchmark",
                 "the postmortem"],
        "tags": ["programacion", "dev", "python", "javascript", "opensource", "ia", "devops",
                 "backend", "frontend", "linux", "100daysofcode", "bug"],
        "domains": ["repos.example", "devblog.example", "docs-demo.example", "stackdemo.example",
                    "charlas.example"],
    },
    "series": {
        "S": ["el final de temporada", "el guion", "el protagonista", "la serie", "el spoiler",
              "la adaptación", "el reparto", "la plataforma", "el capítulo", "el villano",
              "la secuela", "el doblaje"],
        "O": ["el último capítulo", "el tráiler", "la escena del final", "la primera temporada",
              "el documental", "la peli del finde", "el piloto", "la miniserie", "el estreno"],
        "S_en": ["the season finale", "the writing", "the lead", "the show", "the adaptation",
                 "the cast"],
        "O_en": ["the last episode", "the trailer", "the final scene", "the documentary",
                 "the pilot"],
        "tags": ["series", "cine", "estreno", "spoiler", "temporada", "maraton", "peliculas",
                 "streaming", "finaldetemporada", "trailer", "documental", "terror"],
        "domains": ["resenas.example", "cinefilos.example", "queveo.example",
                    "trailers-demo.example", "butaca.example"],
    },
    "viajes": {
        "S": ["el vuelo", "la ruta", "el hostel", "la frontera", "el pasaje", "la valija",
              "el itinerario", "la montaña", "la costa", "el cambio", "el micro", "la escala"],
        "O": ["las fotos del sur", "el video de la ruta", "la guía de la ciudad",
              "el mapa del trekking", "el atardecer de ayer", "la lista de lugares",
              "el camping", "la excursión"],
        "S_en": ["the flight", "the road", "the hostel", "the border", "the itinerary",
                 "the layover"],
        "O_en": ["the photos from the south", "the city guide", "the trekking map",
                 "yesterday's sunset", "the campsite"],
        "tags": ["viajes", "mochileros", "patagonia", "ruta40", "trekking", "playa", "viajar",
                 "wanderlust", "montaña", "roadtrip", "camping", "norte"],
        "domains": ["mapasyrutas.example", "hostelesya.example", "pasajes-demo.example",
                    "bitacora.example", "senderos.example"],
    },
    "mascotas": {
        "S": ["el veterinario", "el refugio", "la adopción", "el paseo", "la vacuna", "el alimento",
              "la plaza", "el adiestramiento", "la castración", "el tránsito", "la correa",
              "el arenero"],
        "O": ["el video del cachorro", "la foto de mi gata", "la campaña de adopción",
              "la jornada de vacunación", "el perro del vecino", "la colecta del refugio",
              "el gato de la oficina", "la feria"],
        "S_en": ["the vet", "the shelter", "adoption", "the walk", "the food", "training"],
        "O_en": ["the puppy video", "my cat's photo", "the adoption drive", "the neighbor's dog",
                 "the shelter fundraiser"],
        "tags": ["mascotas", "adopta", "perros", "gatos", "rescate", "adopcion", "nocompres",
                 "veterinaria", "cachorros", "michis", "refugio", "transito"],
        "domains": ["adoptame.example", "patitas.example", "vetonline-demo.example",
                    "refugios.example", "huellas.example"],
    },
}
GLOBAL_DOMAINS = ["videos.example", "fotos.example", "noticias.example", "enlaces.example"]

NICKS = """nico tincho maru sofi juampi lucho cami fede agus flor santi mati rochi pau gonza eze
facu caro vicky joaco lean seba dani ale luli mica tomi fran gabi nacho pipo toto pato coti juli
marian nahu brai jony charly rama lauti benja emi guada cande abru mili jaz mel""".split()
SYLL = "ra lo mi ta ne ko su pe ga di vo zu ba ti chu le mo fa ri no".split()
HANDLE_WORDS = ["gamer", "ok", "arg", "bsas", "mdq", "cba", "ros", "dev", "fc", "rock", "music",
                "tech", "crypto", "cocina", "viaja", "real", "oficial", "xd"]
FIRST_NAMES = """Nicolás Martín Mariana Sofía Juan Luciano Camila Federico Agustina Florencia
Santiago Matías Rocío Paula Gonzalo Ezequiel Facundo Carolina Victoria Joaquín Leandro Sebastián
Daniela Alejandro Lucía Micaela Tomás Francisco Gabriela Ignacio Julieta Nahuel Brian Jonathan
Carlos Ramiro Lautaro Benjamín Emilia Guadalupe""".split()
SURNAMES = """Ferreyra Quiroga Benítez Sosa Acosta Medina Herrera Aguirre Giménez Molina Castro
Rojas Ortiz Núñez Luna Cabrera Ríos Godoy Morales Domínguez Peralta Vega Carrizo Ojeda Ponce
Vera Maldonado Farías Paz Bustos""".split()
PROFESSIONS = ["diseñador", "programadora", "docente", "periodista", "estudiante de abogacía",
               "kinesiólogo", "contadora", "músico", "fotógrafa", "cocinero", "analista",
               "ingeniero", "community manager", "tatuadora", "electricista", "enfermera",
               "streamer", "editor de video", "librero", "sommelier"]
CITIES = ["Buenos Aires", "Rosario", "Córdoba", "Mendoza", "La Plata", "Mar del Plata", "Salta",
          "Bariloche", "Tucumán", "Neuquén", "Montevideo", "Santa Fe", "Bahía Blanca", "CABA",
          "zona sur"]
QUOTES = ["opiniones propias", "acá por los memes", "mate y a otra cosa", "hincha del que juegue mejor",
          "no doy consejos", "todo pasa", "menos es más", "lo importante es la salud",
          "RT no es aval", "cuenta personal", "vivir y dejar vivir", "en construcción",
          "amante del café", "siempre aprendiendo", "prohibido rendirse"]
BIO_SEPS = [" | ", " · ", ". ", " - ", " / ", "\n"]
TWITTER_CLIENTS = {"android": "Twitter for Android", "iphone": "Twitter for iPhone",
                   "web": "Twitter Web App"}
THIRD_PARTY_CLIENTS = ["TweetDeck", "Buffer", "IFTTT", "Hootsuite Inc.", "Tweetbot for iOS"]
